{% set name = "toad" %}
{% set version = "0.0.65" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/amphibian-dev/{{ name }}.git
  git_rev: {{ version }}

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - toad = toad.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy >=1.20
    - cython  >=0.29.15
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - scipy
    - scikit-learn >=0.21
    - seaborn >=0.10.0

test:
  imports:
    - toad
  commands:
    - toad -h

about:
  home: https://github.com/amphibian-dev/toad
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Toad is developed to facilitate the model development work - especially credit risk scorecard.
  description: |
    Toad is developed to facilitate the model development work - especially credit risk scorecard.
  doc_url: https://toad.readthedocs.io/
  dev_url: https://github.com/amphibian-dev/toad

extra:
  recipe-maintainers:
    - Secbone
